// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAppData;

#nullable disable

namespace TestAppData.Migrations
{
    [DbContext(typeof(TestAppContext))]
    [Migration("20220624102536_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("TestAppData.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdReport");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Comment");

                    b.Property<string>("HtmlString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HtmlReport");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NameReport");

                    b.Property<bool?>("Result")
                        .HasColumnType("boolean")
                        .HasColumnName("Result");

                    b.Property<string>("XmlString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("XmlReport");

                    b.HasKey("Id");

                    b.ToTable("testResults");
                });
#pragma warning restore 612, 618
        }
    }
}
